export const RULES = {
  // Position limits
  MIN_POSITIONS: 4,
  MAX_POSITIONS: 8,
  MAX_SINGLE_POSITION_PCT: 25,
  MAX_SECTOR_PCT: 40,
  MAX_MEGA_CAP_PCT: 30,
  MIN_SECTORS: 3,

  // Cash management
  MIN_CASH_PCT: 5,
  MAX_CASH_PCT: 20,
  CASH_DEPLOY_DAYS: 10,

  // Score thresholds
  MIN_ENTRY_SCORE: 65,
  STRONG_BUY_MIN: 80,
  BUY_MIN: 65,
  HOLD_MIN: 50,

  // Market cap thresholds (in dollars)
  SMALL_CAP_MAX: 10_000_000_000,
  MID_CAP_MAX: 50_000_000_000,
  LARGE_CAP_MAX: 200_000_000_000,
  MEGA_CAP_MAX: 500_000_000_000,

  // Liquidity
  MIN_AVG_DAILY_VOLUME: 5_000_000,
  MAX_BID_ASK_SPREAD: 0.005,

  // Correlation
  MAX_PAIRWISE_CORRELATION: 0.75,
  MAX_PORTFOLIO_AVG_CORRELATION: 0.60,
  MAX_HIGH_CORRELATION_PAIRS: 2,
  HIGH_CORRELATION_THRESHOLD: 0.70,

  // Drawdown escalation
  DRAWDOWN_REVIEW: 0.10,
  DRAWDOWN_RESCORE: 0.15,
  DRAWDOWN_AUTO_EXIT: 0.20,
  DRAWDOWN_FORCED_EXIT: 0.25,
  PORTFOLIO_HALT_THRESHOLD: -0.12,

  // Timing
  EARNINGS_BLACKOUT_DAYS: 3,
  COOLDOWN_DAYS: 90,

  // Donchian
  DONCHIAN_REJECT_PCT: 0.95,
  DONCHIAN_PREFER_PCT: 0.60,

  // Position sizing
  BASE_ALLOC_BUY: { min: 10, max: 15 },
  BASE_ALLOC_STRONG_BUY: { min: 15, max: 25 },
  SIGNAL_BOOST_PCT: 3,
  HIGH_BETA_PENALTY_PCT: 3,
  CORRELATION_PENALTY_PCT: 5,

  // Quant signal adjustments
  MOMENTUM_BOOST: 5,
  SUE_BOOST: 5,
  REVISION_BOOST: 4,
  VALUE_BOOST: 3,
  DEATH_CROSS_PENALTY: -5,
  HIGH_BETA_PENALTY: -3,
  HIGH_BETA_THRESHOLD: 1.8,

  // Research split
  AGI_RESEARCH_PCT: 60,
  BROAD_RESEARCH_PCT: 40,
} as const;
